[workspace]
members = [
    "runner",
]
exclude = [
    "2015", 
    "2016", 
    "2017", 
    "2018", 
    "2019", 
    "2020", 
    "2021", 
    "2022",
    "new_year"
]
resolver = "2"

[profile.release]
debug = true
lto = "thin"
