[workspace]
members = [
    "new_year",
    "runner",
    "runner/helper",
]
exclude = [
    "2015", 
    "2016", 
    "2017", 
    "2018", 
    "2019", 
    "2020", 
    "2021", 
    "2022"
]
resolver = "2"

[profile.release]
debug = true
