[package]
name = "runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
chrono = "0.4.31"
clap = "4.4.8"
minreq = { version = "2.11.0", features = ["https"] }
